var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

var finalName = "";

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function getRandomQuote() {
    const quotes = [
        "Nice!",
        "I agree!",
        "Wow!",
        "Inspiring!",
        "Awesome!",
        "Hello there!",
        "Greetings!",
        "Any updates?",
        "Loving it!",
        "More please!",
        "Cool!",
        "👍",
        "Keep them coming!",
        "This is great!",
        "Thanks!",
        "Hi!",
        "What's up?",
        "Feeling motivated!",
        "😄",
        "Impressive!",
        "Bravo!",
        "Fantastic!",
        "Absolutely!",
        "Right on!",
        "You got this!",
        "Wonderful!",
        "Excellent!",
        "Incredible!",
        "Absolutely amazing!",
        "Beautiful!",
        "Superb!",
        "Terrific!",
        "Outstanding!",
        "Remarkable!",
        "Spectacular!",
        "Stunning!",
        "Phenomenal!",
        "Magnificent!",
        "Marvelous!",
        "Astonishing!",
        "Gorgeous!",
        "Lovely!",
        "Fabulous!",
        "Exceptional!",
        "Out of this world!",
        "Mind-blowing!",
        "Impressive work!",
        "You're a rockstar!",
        "Inspired by this!",
        "This is pure gold!",
        "So true!",
        "Couldn't agree more!",
        "Absolutely right!",
        "100%!",
        "Totally agree!",
        "Exactly!",
        "Spot on!",
        "Well said!",
        "Perfect!",
        "Couldn't have said it better!",
        "You nailed it!",
        "You're on fire!",
        "Nailed it!",
        "Absolutely spot on!",
        "You hit the nail on the head!",
        "Couldn't be more accurate!",
        "Precisely!",
        "You're so wise!",
        "So much wisdom!",
        "This is wisdom in a nutshell!",
        "Inspirational!",
        "Motivational!",
        "Encouraging!",
        "Uplifting!",
        "Positive vibes!",
        "Sending positive energy!",
        "Feeling inspired!",
        "Keep it up!",
        "You're amazing!",
        "Believe in yourself!",
        "Stay positive!",
        "Dream big!",
        "Never give up!",
        "Keep moving forward!",
        "You're a star!",
        "Chasing dreams!",
        "The sky's the limit!",
        "Seize the day!",
        "Carpe Diem!",
        "Embrace the journey!",
        "Stay strong!",
        "You're unstoppable!",
        "You've got this!",
        "Make it happen!",
        "You're a champion!",
        "Success awaits!",
        "Keep pushing!",
        "Keep shining!",
        "You're a winner!",
        "Follow your heart!",
        "Stay focused!",
        "Stay determined!",
        "Keep going!",
        "Never back down!",
        "Stay positive and positive things will happen!",
        "Shine bright like a diamond!",
        "Dream it, achieve it!",
        "Create your own destiny!",
        "You're a legend!",
        "Live with passion!",
        "Believe in your dreams!",
        "Persistence pays off!",
        "Determination leads to success!",
        "Stay motivated!",
        "Stay hungry for success!",
        "You're a force to be reckoned with!",
        "Stay true to yourself!",
        "You're one of a kind!",
        "Keep your head up!",
        "Stay inspired!",
        "Keep the faith!",
        "Follow your bliss!",
        "Never stop dreaming!",
        "You're a true inspiration!",
        "You inspire greatness!",
        "Keep the positivity flowing!",
        "Live life to the fullest!",
        "You're unstoppable!",
        "Stay positive and positive things will happen!",
        "Shine bright like a diamond!",
        "Dream it, achieve it!",
        "Create your own destiny!",
        "You're a legend!",
        "Live with passion!",
        "Believe in your dreams!",
        "Persistence pays off!",
        "Determination leads to success!",
        "Stay motivated!",
        "Stay hungry for success!",
        "You're a force to be reckoned with!",
        "Stay true to yourself!",
        "You're one of a kind!",
        "Keep your head up!",
        "Stay inspired!",
        "Keep the faith!",
        "Follow your bliss!",
        "Never stop dreaming!",
        "You're a true inspiration!",
        "You inspire greatness!",
        "Keep the positivity flowing!",
        "Live life to the fullest!",
        "You're unstoppable!",
        "Stay positive and positive things will happen!",
        "Shine bright like a diamond!",
        "Dream it, achieve it!",
        "Create your own destiny!",
        "You're a legend!",
        "Live with passion!",
        "Believe in your dreams!",
        "Persistence pays off!",
        "Determination leads to success!",
        "Stay motivated!",
        "Stay hungry for success!",
        "You're a force to be reckoned with!",
        "Stay true to yourself!",
        "You're one of a kind!",
        "Keep your head up!",
        "Stay inspired!",
        "Keep the faith!",
        "Follow your bliss!",
        "Never stop dreaming!",
        "You're a true inspiration!",
        "You inspire greatness!",
        "Keep the positivity flowing!",
        "Live life to the fullest!",
      ];
  
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
  }
